apiVersion: v1
kind: Service
metadata:
  name: web-html-lb
spec:
  selector:
    app: web-html
  ports:
    - port: 80 #porta do meu container
      targetPort: 80 #porta do meu loadBalancer
  type: LoadBalancer
