apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin123
        - name: MYSQL_DATABASE
          value: mydb
        ports:
        - containerPort: 3306 
          name: mysql

        volumeMounts:
        - name: local
          mountPath: /var/lib/mysql # caminho no container
      volumes:
      - name: local
        hostPath:
          path: /mydb/ # volume local no host/node