apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    type: local
spec:
  capacity: # capacidade do meu VOLUME
    storage: 100Mi
  volumeMode: Filesystem
  accessModes: #
    - ReadWriteOnce # o volume pode ser montado como leitura-gravação por um único nó
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual # identificação para vincular o PVC com o PV
  hostPath: 
    path: /mydatabase/ # local onde será o diretório em que serão armazenados os dados desse volume