apiVersion: v1
kind: Pod
metadata:
  name: app-phpv2
spec:
  containers:
    - name: app-phpv2
      image: adrielcarmo/app-php-teste:2.0
      ports:
      - containerPort: 80
      
---

apiVersion: v1
kind: Service
metadata:
  name: app-phpv2-svc
spec:
  type: NodePort
  selector:
    app: app-phpv2
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 32000

