apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env: 
    - name: "MYSQL_DATABASE"
      value: meudb
    - name: "MYSQL_ROOT_PASSWORD" 
      value: "lasanha123" # nao é aconselhável passar a senha diretamente aq, e sim através de secret
    ports:
      - containerPort: 3306
