apiVersion: v1
kind: Service
metadata:
  name: lb-app-php
spec:
  type: LoadBalancer
  selector:
    app: php-app
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  clusterIP: None

