apiVersion: v1
kind: Pod
metadata:
  name: myapp-html
  labels:
    name: myapp-html
spec:
  containers:
  - name: myapp-html
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    - containerPort: 443