machines = {
  "master" => {"memory" => "512", "cpu" => "1", "image" => "ubuntu/jammy64", "ip" => "172.16.2.230"},
  "node01" => {"memory" => "512", "cpu" => "1", "image" => "ubuntu/jammy64", "ip" => "172.16.2.162"},
  "node02" => {"memory" => "512", "cpu" => "1", "image" => "ubuntu/jammy64", "ip" => "172.16.2.33"},
  "node03" => {"memory" => "512", "cpu" => "1", "image" => "ubuntu/jammy64", "ip" => "172.16.3.79"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf| 
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "public_network", ip: "#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
      end
      
      machine.vm.provision "shell", path: "instalar-docker.sh"
      
      if "#{name}" == "master"
        machine.vm.provision "shell", path: "master.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end
      
    end
  end
end