apiVersion: v1
kind: Service
metadata:
  name: app-php
spec:
  type: NodePort
  selector:
    app: app-php
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 30007 porta de acesso a este serviço, deve ser acima de 30000
      #se o nodePort nao for adicionado, o k8s irá atribuir uma porta aleatória a este serviço